In [2]:
!pip3 install tensorflow pandas numpy 


In [3]:
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers import Input

In [6]:

training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

target_data = np.array([[0],[1],[1],[0]], "float32")

model = Sequential()
model.add(Input(shape = (2,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mse', optimizer='sgd', metrics=['accuracy'])
print(model.summary())

model.fit(training_data, target_data, epochs=2000, verbose = 0, batch_size = 1)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 16)                48        
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 65
Trainable params: 65
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
print(model.predict(np.array([[1,0],[1,1]], "float32")))

[[0.871457 ]
 [0.1624924]]


In [30]:
import keras
from keras.datasets import mnist
    
(x_train, y_train), (x_test, y_test) = mnist.load_data()

num_classes = 10
y_train = keras.utils.np_utils.to_categorical(y_train, num_classes)
y_test = keras.utils.np_utils.to_categorical(y_test, num_classes)

x_train = x_train.reshape(x_train.shape[0], 784)
x_test = x_test.reshape(x_test.shape[0], 784)

In [38]:
model = Sequential()

model.add(Input(shape = (784,)))
model.add(Dense(units=32, activation='sigmoid'))
model.add(Dense(units=64, activation='sigmoid'))
model.add(Dense(units=32, activation='sigmoid'))
model.add(Dense(units=10, activation='softmax'))
model.summary()

model.compile(optimizer="sgd", loss='mse', metrics=['accuracy'])

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_36 (Dense)            (None, 32)                25120     
                                                                 
 dense_37 (Dense)            (None, 64)                2112      
                                                                 
 dense_38 (Dense)            (None, 32)                2080      
                                                                 
 dense_39 (Dense)            (None, 10)                330       
                                                                 
Total params: 29,642
Trainable params: 29,642
Non-trainable params: 0
_________________________________________________________________


In [49]:
import time
start = round(time.time() * 1000)
history = model.fit(x_train, y_train, batch_size=32, epochs=100, verbose=False)
end = round(time.time() * 1000) - start

print("Final Loss : ")
print(history.history['loss'][-1])
print("Totalt time : "+str(end / (60 * 1000))+" minutes")

Final Loss : 
0.011155173182487488
Totalt time : 2.9736 minutes


In [50]:
import random

test_sample_x = []
test_sample_y = []
for i in range(0,10):
    r = random.randint(0, 5000)
    test_sample_x.append(x_test[r])
    test_sample_y.append(y_test[r])

predict = model.predict(np.array(x_test))

for i in range(0,10):
    print("Number :")
    print(test_sample_y[i])
    print("Output :")
    print(predict[i])

Number :
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Output :
[5.3856294e-03 2.5307725e-06 1.6147406e-04 2.0335196e-03 1.7155228e-03
 5.3807907e-04 9.8692572e-06 9.6935141e-01 5.7662474e-03 1.5035731e-02]
Number :
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Output :
[3.84759950e-03 8.58976506e-04 9.67691481e-01 1.92052010e-03
 8.98561048e-05 1.08638005e-02 1.04220593e-02 2.69944412e-05
 4.27725958e-03 1.39199983e-06]
Number :
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
Output :
[2.0304961e-07 9.7031838e-01 5.7087787e-03 5.1118531e-03 5.7437940e-04
 1.8267490e-03 3.3789671e-03 3.4639374e-06 1.0426474e-02 2.6507177e-03]
Number :
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Output :
[9.4541782e-01 8.1720583e-07 5.5252700e-03 1.0130381e-03 1.2005535e-03
 3.1373288e-02 8.9906290e-04 1.1808856e-02 2.7504449e-03 1.0901089e-05]
Number :
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Output :
[1.7918674e-03 4.3806364e-04 4.5128661e-04 7.6683493e-05 9.1489840e-01
 8.0678649e-03 4.2459525e-02 5.2808849e-03 5.1516802e-03 2.1383781e-02]
Number :
[0. 1. 0. 0. 0.