In [2]:
import numpy as np
from numpy import ndarray

In [8]:
a = np.arange(0,120)
a = a.reshape(2,3,4,5)
print (a.shape)
print (a)
a = np.transpose(a, [2,3,0,1])
print (a.shape)
print(a)


(2, 3, 4, 5)
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]
(4, 5, 2, 3)
[[[[  0  20  40]
   [ 60  80 100]]

  [[  1  21  41]
   [ 61  81 101]]

  [[  2  22  42]
   [ 62  82 102]]

  [[  3  23  43]
   [ 63  83 103]]

  [[  4  24  44]
   [ 64  84 104]]]


 [[[  5  25  45]
   [ 65  85 105]]

  [[  6  26  46]
   [ 66  86 106]]

  [[  7  27  47]
   [ 67  87 107]]

  [[  8  28  48]
   [ 68  88 108]]

  [[  9  29  49]
   [ 69  89 109]

In [30]:
x = np.random.binomial(5, 0.3,size=10)
print(x)

[2 1 1 1 0 0 2 2 1 3]


In [75]:
mat_a = np.full((4,3,3,3), 1)
mat_b = np.full((3,2), 2)
resultab = np.matmul(mat_a,mat_b)
# resultba = np.matmul(mat_b,mat_a)
print(mat_a.shape)
print(mat_a)
print()
print(mat_b.shape)
print(mat_b)
print()
print(resultab.shape)
print(resultab)
print()
# print(resultba.shape)
# print(resultba)

(4, 3, 3, 3)
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]

(3, 2)
[[2 2]
 [2 2]
 [2 2]]

(4, 3, 3, 2)
[[[[6 6]
   [6 6]
   [6 6]]

  [[6 6]
   [6 6]
   [6 6]]

  [[6 6]
   [6 6]
   [6 6]]]


 [[[6 6]
   [6 6]
   [6 6]]

  [[6 6]
   [6 6]
   [6 6]]

  [[6 6]
   [6 6]
   [6 6]]]


 [[[6 6]
   [6 6]
   [6 6]]

  [[6 6]
   [6 6]
   [6 6]]

  [[6 6]
   [6 6]
   [6 6]]]


 [[[6 6]
   [6 6]
   [6 6]]

  [[6 6]
   [6 6]
   [6 6]]

  [[6 6]
   [6 6]
   [6 6]]]]



In [3]:
param_size = 5
param_pad = 2

def _pad_1d(inp: ndarray) -> ndarray:
    z = np.array([0])
    z = np.repeat(z, param_pad)
    return np.concatenate([z, inp, z])

def _pad_1d_batch(inp: ndarray) -> ndarray:
    outs = [_pad_1d(obs) for obs in inp]
    return np.stack(outs)

def _pad_2d_obs(inp: ndarray):
   
    inp_pad = _pad_1d_batch(inp)
    other = np.zeros((param_pad, inp.shape[0] + param_pad * 2))
    return np.concatenate([other, inp_pad, other])

def _pad_2d_channel(inp: ndarray):
    return np.stack([_pad_2d_obs(channel) for channel in inp])

In [4]:
def _get_image_patches(input_: ndarray):
    imgs_batch_pad = np.stack([_pad_2d_channel(obs) for obs in input_])
    print("After Padding : ")
    print(imgs_batch_pad.shape)
    patches = []
    img_height = imgs_batch_pad.shape[2]
    for h in range(img_height-param_size+1):
        for w in range(img_height-param_size+1):
            patch = imgs_batch_pad[:, :, h:h+param_size, w:w+param_size]
            patches.append(patch)
    return np.stack(patches)

In [19]:
x = np.arange(0, 10 * 3 * 6 * 6).reshape(10,3,6,6)

patches = []
strPatches = []
img_height = x.shape[2]
for h in range(5):
    for w in range(5):
        patch = x[:, :, h:h+2, w:w+2]
        patches.append(patch)
        strPatches.append(np.array2string(patch.reshape((120,))))
        
x = np.stack(patches)

print(x.shape)
print(np.array(strPatches))

(25, 10, 3, 2, 2)
['[   0    1    6    7   36   37   42   43   72   73   78   79  108  109\n  114  115  144  145  150  151  180  181  186  187  216  217  222  223\n  252  253  258  259  288  289  294  295  324  325  330  331  360  361\n  366  367  396  397  402  403  432  433  438  439  468  469  474  475\n  504  505  510  511  540  541  546  547  576  577  582  583  612  613\n  618  619  648  649  654  655  684  685  690  691  720  721  726  727\n  756  757  762  763  792  793  798  799  828  829  834  835  864  865\n  870  871  900  901  906  907  936  937  942  943  972  973  978  979\n 1008 1009 1014 1015 1044 1045 1050 1051]'
 '[   1    2    7    8   37   38   43   44   73   74   79   80  109  110\n  115  116  145  146  151  152  181  182  187  188  217  218  223  224\n  253  254  259  260  289  290  295  296  325  326  331  332  361  362\n  367  368  397  398  403  404  433  434  439  440  469  470  475  476\n  505  506  511  512  541  542  547  548  577  578  583  584  613  614\

In [35]:
ystack = np.stack([y,y2])
print(ystack.shape)
z = ystack[:,0:6,0:6]
print(z)
print(z.shape)

(2, 2, 6, 6)
[[[[0.         0.         0.         0.         0.         0.        ]
   [0.         0.23304772 0.98384247 0.81551024 0.9005728  0.        ]
   [0.         0.63205792 0.98053236 0.30233281 0.10789035 0.        ]
   [0.         0.57802202 0.27511093 0.33970653 0.58098165 0.        ]
   [0.         0.9585799  0.09899673 0.3102443  0.79259248 0.        ]
   [0.         0.         0.         0.         0.         0.        ]]

  [[0.         0.         0.         0.         0.         0.        ]
   [0.         0.65982999 0.72268053 0.46515405 0.68570829 0.        ]
   [0.         0.35104588 0.83263061 0.76708484 0.84883519 0.        ]
   [0.         0.40369771 0.64776215 0.34107281 0.79989446 0.        ]
   [0.         0.00289287 0.39145337 0.84717662 0.85489297 0.        ]
   [0.         0.         0.         0.         0.         0.        ]]]


 [[[0.         0.         0.         0.         0.         0.        ]
   [0.         0.23304772 0.98384247 0.81551024 0.9005728 

In [21]:
m = np.arange(1,4).reshape(1,3)
n = np.arange(1,10).reshape(3,3)

print(m+n)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
